### ISSUE TITLE
Crear el perfil del perro

### ISSUE THREAD

**Issue by joserh94** [scastro93/DogLove#11]
Con esto nos referimos al perfil ya dentro de la aplicación, crear algo parecido a un CRUD donde puedas borrar o modificar, etc.

**Comment by DiegoNoe** [comment]
FALTA terminar de definir este issue, es terminar de crear el perfil, esto para posible expansión a tener varios perros dentro de la misma cuenta.

**Comment by DiegoNoe** [comment]
Listo! ya esta la branch doglove_11

**Comment by joserh94** [comment]
Hola pero que pasa con la imagen del perro?

**Comment by HectorHF** [comment]
¿Qué tiene la imagen?
