### ISSUE TITLE
View Settings

### ISSUE THREAD

**Issue by joserh94** [scastro93/DogLove#19]

**Comment by scastro93** [comment]
En esta vista se mostrará la ventana de settings, aqua se van a ver las opciones a modificar. por ej. el nombre, la dirección, el teléfono, etc.

**Comment by neymgm** [comment]
- Modificar datos de usuario

- Modificar datos de mascota

- Borrar cuenta

**Comment by joserh94** [comment]
Esto seguira existiendo?

**Comment by HectorHF** [comment]
Lo más apropiado para mí es que siga existiendo, no sé qué opinen ustedes.

**Comment by neymgm** [comment]
Hay que poner un botón en el Tab de perfil que lleve a una página que tenga un formulario con los campos de la base de datos que el usuario puede editar. Y ahí mismo poner un botón de "Delete account"

**Comment by HectorHF** [comment]
De acuerdo!

**Comment by joserh94** [comment]
Okay, pueden ir haciendo de que el front end y ya en un rato me echo el back end, abrire el issue para el backend de settings

**Comment by joserh94** [comment]
Estaba pensando, que tal si ponen un engrane a la derecha de cada una de las cosas que sean modificables y que cuando le des click salga un pop up con un textfield, y ya ahi pueden escribir el nuevo valor y este de que cancelar o guardar, si le dan en guardar solo se triggerea la funcion correspondiente (eso lo hgao yo u otra persona de backend) y ya

**Comment by HectorHF** [comment]
Me parece buena idea, la iré haciendo.

**Comment by HectorHF** [comment]
Ya hice la página, pero hay que definir bien qué vamos a dejar y qué a quitar. Por el momento me basé mucho en lo que teníamos en el registro (falta conectar con Firebase).

**Comment by joserh94** [comment]
Listo :)
