### ISSUE TITLE
Unir el front-end del login y registro con el back-end

### ISSUE THREAD

**Issue by joserh94** [scastro93/DogLove#26]

**Comment by joserh94** [comment]
Estamos intentando hacer la union más facil, para que solo sea editar de que el css y el body del html

**Comment by neymgm** [comment]
Ya se hace el Login pero se requiere mejorar el diseño. El cliente está contento con el resultado pero se puede mejorar.

**Comment by HectorHF** [comment]
Se añadió color de fondo y se mejoró diseño de los campos de texto. Se aceptan sugerencias con respecto al color.

**Comment by joserh94** [comment]
cool, lo cerrare
