### ISSUE TITLE
Modal de aviso de match

### ISSUE THREAD

**Issue by scastro93** [scastro93/DogLove#27]
es un modal en la pantalla de dashboard donde se da un aviso confirmando match, tiene que decir que la información de la otra persona se verá en la pestaña de matches

**Comment by neymgm** [comment]
Ya se muestra el modal cuando hay un match entre perros.

![23698424_10214415843652041_249960239_o](https://user-images.githubusercontent.com/7617365/32919439-7214767c-caeb-11e7-8497-a21e5130806d.png)
