### ISSUE TITLE
Manejar las Fotos

### ISSUE THREAD

**Issue by joserh94** [scastro93/DogLove#33]
Agregar foto de perro y que se muestre

**Comment by joserh94** [comment]
Se tiene que hacer ya sea en perfil o en el registro que se pueda subir la foto del perro y tambien se tiene que hacer que en la lista de los perros se muestre la foto del perro

**Comment by HectorHF** [comment]
Se agregó la posibilidad de subir foto en el registro. Falta hacerlo en backend.

**Comment by HectorHF** [comment]
¿Si se va a hacer esto? Alguien lo quitó de la página de registro.
