### ISSUE TITLE
Documentos

### ISSUE THREAD

**Issue by HectorHF** [scastro93/DogLove#39]
Para la entrega final hay que tener esto:

1. Historias actualizadas.
2. Sprint actualizados.
3. Gráfica de Velocity actualizada.
4. Burndown chart.
5. Frecuency and Severity Matrix
6. Pruebas, formato que deseen.
7. Software terminado.

¿Qué cosas de aquí ya están?

**Comment by neymgm** [comment]
Se terminaron los documentos a tiempo para entrega
