### ISSUE TITLE
Crear Lista de Animales

### ISSUE THREAD

**Issue by joserh94** [scastro93/DogLove#6]
Conexion de la lista front con FireBase

**Comment by DiegoNoe** [comment]
Crear el querie en el que se pide la lista de animales por ver y se genere, teniendo en cuenta que la lista es un poco "inteligente" sabe los animales que ya viste y los que no, para los cuales se empezara a matchear o a borrar. La implementación será unicamente con un numero de referencia y los animales eran indexados en orden, así se sabrá cuales animales ya se vieron antes.

**Comment by joserh94** [comment]
Si, ya se creo la lista y se creo medio inteligentes

**Comment by DiegoNoe** [comment]
Listo, revisa los que ya has visto y no te los vuelve a mostrar, ahora mismo hago el pull request
