### ISSUE TITLE
Mostrar Animal

### ISSUE THREAD

**Issue by joserh94** [scastro93/DogLove#7]
Mostrar el animal a likear o no likear, esto es iterar dentro de la firebase para poder mostrarlos

**Comment by DiegoNoe** [comment]
Igual que el pasado, pero ahora para desplegar, jalar la lista de los que no se han visto.

**Comment by joserh94** [comment]
Si pero pero a esto todavia, tenems que validad que tu no estes y ademas comparar que los dos se tengan

**Comment by DiegoNoe** [comment]
Ah si tienes razón, como lo discutimos en clase, no?

**Comment by DiegoNoe** [comment]
Ya quedó, quedó como parte del issue 6, en la branch doglove_6
