### ISSUE TITLE
Guardar perfil likeado FIBO8

### ISSUE THREAD

**Issue by joserh94** [scastro93/DogLove#9]
Aqui guardamos la instancia del perfil likeado en mi propio perfil, se crea la lista de animales likeados por mi

**Comment by DiegoNoe** [comment]
De no ser match, guardar el perfil likeado en la lista propia.

**Comment by joserh94** [comment]
Este issue tambien fue el que genero la alerta? o el metodo para la alerta? lo cerrare de por si
